title: Mr. Clevenger's Website
description: Information and Repositories for Mr. Clevenger's classes at Blue Springs High School
author:
  name: Mr. Clevenger
  email: "kclevenger@bssd.net"
remote_theme: jekyll-theme-slate
