title: Mr. Clevenger's Website
description: Information and Repositories for Mr. Clevenger's classes at Blue Springs High School
author:
  name: Mr. Clevenger
  email: "kclevenger@bssd.net"
header_pages:
  - ap-csp.md
  - ap-cs-a.md
  - cse.md
  - cyber.md
social-network-links:
  email: "kclevenger@bssd.net"
  github: kclevenger84
remote_theme: ys1998/academic-portfolio